### ISSUE TITLE
Outdated build instructions in the Readme file

### ISSUE THREAD

**Issue by ArtunSubasi** [korlibs/korge-hello-world#11]
_Tested on Ubuntu 18.04.5 LTS_

- The `Compiling for Native Desktop` section of the `Readme` file lists gradle tasks that do not exist. After a fresh checkout, I could build a native Linux binary using `./gradlew linkReleaseExecutableLinuxX64` instead.
- The `Cross-Compiling for Linux/Windows` section lists scripts which start docker. However, running them leads to the following auth error:

`docker: Error response from daemon: Get https://registry-1.docker.io/v2/soywiz/kotlin-native-win/manifests/java8: unauthorized: incorrect username or password.`

I couldn't find any instructions about docker authentication to pull the references image `soywiz/kotlin-native-win:java8`

**Comment by soywiz** [comment]
Was not aware of this issue, the last time I tried it worked just fine. In fact the kotlin-native-win is publicly published on the docker registry here: https://hub.docker.com/repository/docker/soywiz/kotlin-native-win
Can you access that page? Could it be that you have a special docker configuration somehow? (like specifying the user/password) or that it is a temporal problem with docker registry?

**Comment by ArtunSubasi** [comment]
My bad. Any `docker pull *` command lead to the same problem. I guess my docker configuration was outdated. Calling `docker logout` did the trick.

Maybe you may have a look at the first issue. The Readme lists `./gradlew linkMainDebugExecutableLinuxX64`. I looked at the gradle plugin code but couldn't find out where `MainDebug` comes from.

I can build via `./gradlew linkReleaseExecutableLinuxX64` or `./gradlew linkDebugExecutableLinuxX64` instead.

**Comment by soywiz** [comment]
Sure, it seems that that was changed at some point by the kotlin plugin.
