### ISSUE TITLE
compileKotlinJs task fails with "Could not find "org.jetbrains.kotlinx:kotlinx-coroutines-core"" in IntelliJ CE 2020.3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by exertionriver** [korlibs/korge-hello-world#14]
After cloning current repo.

Further details:
```
Could not find "org.jetbrains.kotlinx:kotlinx-coroutines-core" in [.../.local/share/kotlin/daemon].
```

May be related to [korge-samples #41](https://github.com/korlibs/korge-samples/issues/41)

Thank you,
Ian

**Comment by soywiz** [comment]
Can you try with java 8?
Can you share privately with me your environment variables (masking all the sensitive information) via discord?
Do you have an `~/.m2/repositories` and `~/.gradle` folders?

**Comment by exertionriver** [comment]
Hi @soywiz,

No change running task runNative (at language level 8) using 
```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment Corretto-8.282.08.1 (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM Corretto-8.282.08.1 (build 25.282-b08, mixed mode)
```
fails with
```
Could not find "org.jetbrains.kotlinx:atomicfu-cinterop-interop" in [/.../dev/korge-hello-world, /.../.konan/klib, /.../.konan/kotlin-native-prebuilt-linux-1.4.30/klib/common, /.../.konan/kotlin-native-prebuilt-linux-1.4.30/klib/platform/linux_x64].
```
similar to [korge-samples issue 41](https://github.com/korlibs/korge-samples/issues/41#issuecomment-785852597)

**Comment by exertionriver** [comment]
Hi @soywiz,

```~/.m2/repositories``` and ```~/.gradle``` folders are present.

I can see both:
```atomicfu-0.15.1.jar``` (from 2021-02-23) in ```~/.m2/repository/org/jetbrains/kotlinx/atomicfu/0.15.1/```, and
```kotlinx-coroutines-core-1.4.2.jar``` (from 2021-01-24) in ```~/.m2/repository/org/jetbrains/kotlinx-coroutines-core/1.4.2```

env variables are the same as what they've been, building K/N projects over the past few months. There is no entry for JAVA_HOME if that helps.

I can look into connecting via discord.

Thank you,
Ian

**Comment by soywiz** [comment]
Can you execute these commands? :
```
./gradlew --stop
./gradlew clean
./gradlew :sample:hello-world:showKorgeVersions
```

**Comment by exertionriver** [comment]
Running ```--stop``` and ```clean``` and then ```./gradlew :showKorgeVersions``` from ```korge-hello-world``` reveals

```
> Task :showKorgeVersions
Build-time:
 - os.name: Linux
 - os.version: 5.4.0-66-generic
 - java.vendor: Ubuntu
 - java.version: 11.0.10
 - gradle.version: Gradle 6.8.1
 - groovy.version: 2.5.12
 - kotlin.version: 1.4.20
Korge Gradle plugin:
 - GIT: v2.0.7.1-dirty
 - KRYPTO: 2.0.6
 - KLOCK: 2.0.6
 - KDS: 2.0.7
 - KMEM: 2.0.7
 - KORMA: 2.0.7
 - KORIO: 2.0.8
 - KORIM: 2.0.7
 - KORAU: 2.0.7
 - KORGW: 2.0.7
 - KORGE: 2.0.7
 - KOTLIN: 1.4.30
 - JNA: 5.7.0
 - COROUTINES: 1.4.2
 - ANDROID_BUILD: 4.0.1
```

Thank you,
Ian

**Comment by soywiz** [comment]
Just to be sure: stopping gradle, cleaning stuff, and removing .m2, .gradle and .konan folders didn't help, like happened here: https://github.com/korlibs/korge-samples/issues/41 ,  right?

**Comment by exertionriver** [comment]
building all targets (including Js) shown in build.gradle.kts from within IntelliJ CE 2020.3 now works, following the steps advised in [korge-samples issue 41](https://github.com/korlibs/korge-samples/issues/41)

Thank you,
Ian

**Comment by soywiz** [comment]
Awesome. Feel free to reopen the issue if required
