### ISSUE TITLE
Cannot access 'kotlin.reflect.KAnnotatedElement' which is a supertype of 'kotlin.reflect.KMutableProperty0'. Check your module classpath for missing or conflicting dependencies

### ISSUE THREAD

**Issue by Ayfri** [korlibs/korge-hello-world#15]
Hi, I started using Korge yesterday, and when using the Hello World (and even the 2048 game), I get in some places this error by Intellij :

I didn't modify any file and I installed the Korge plugin.

`Cannot access 'kotlin.reflect.KAnnotatedElement' which is a supertype of 'kotlin.reflect.KMutableProperty0'. Check your module classpath for missing or conflicting dependencies`

![image](https://user-images.githubusercontent.com/34159136/116696680-8381bf00-a9c2-11eb-9327-2ded0ac462f7.png)

**But the game launches!**

**Comment by soywiz** [comment]
Hey Ayfri! I noticed that same issue. I believe that's related to IDE support, that is somehow breaking in the latest published version. Hopefully the Kotlin team will fix that. I'll create an issue on the Kotlin bugtracker and will link here. Thanks for reporting!

**Comment by soywiz** [comment]
Reported here: https://youtrack.jetbrains.com/issue/KT-46434 going to move to paused/waiting for response since now it is a separate issue

**Comment by jobe-m** [comment]
Closing this issue since the original error was fixed.
