### ISSUE TITLE
Errors when running `gradlew runJvm` on Windows: #25: glGetError after glGenVertexArrays

### ISSUE THREAD

**Issue by darthdeus** [korlibs/korge-hello-world#18]
Cloning the hello world repo and running `.\gradlew runJvm` prints the following in the console

```
> Task :runJvm
NOT Using DisplayLink
running: Thread[main,5,main]
#1: COMPUTED REFRESH RATE for D3DGraphicsDevice[screen=0] (100)
wglCreateContextAttribsARB.error: 0
#25: hWnd: native@0x120b3e, hDC: native@0x61011f3d, hRC: native@0x20000, component: com.soywiz.korgw.awt.AwtGameWindow$frame$1[frame0,1455,416,530x559,layout=java.awt.BorderLayout,title=Korge,resizable,normal,defaultCloseOperation=HIDE_ON_CLOSE,rootPane=javax.swing.JRootPane[,9,38,512x512,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
#25: GL_VERSION: 3.3.0 NVIDIA 471.11, GL_VENDOR: NVIDIA Corporation
#25: GL_RED_BITS: 0, GL_GREEN_BITS: 0, GL_BLUE_BITS: 0, GL_ALPHA_BITS: 0, GL_DEPTH_BITS: 0, GL_STENCIL_BITS: 0
#25: requestCoreProfile=true, isCore=true, extensions=390
wglCreateContextAttribsARB.error: 0
#25: hWnd: native@0x120b3e, hDC: native@0x61011f3d, hRC: native@0x10001, component: com.soywiz.korgw.awt.AwtGameWindow$frame$1[frame0,1455,416,530x559,layout=java.awt.BorderLayout,title=Korge,resizable,normal,defaultCloseOperation=HIDE_ON_CLOSE,rootPane=javax.swing.JRootPane[,9,38,512x512,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
#25: GL_VERSION: 3.3.0 NVIDIA 471.11, GL_VENDOR: NVIDIA Corporation
#25: GL_RED_BITS: 0, GL_GREEN_BITS: 0, GL_BLUE_BITS: 0, GL_ALPHA_BITS: 0, GL_DEPTH_BITS: 0, GL_STENCIL_BITS: 0
#25: requestCoreProfile=true, isCore=true, extensions=390
wglCreateContextAttribsARB.error: 0
#25: hWnd: native@0x120b3e, hDC: native@0x61011f3d, hRC: native@0x10002, component: com.soywiz.korgw.awt.AwtGameWindow$frame$1[frame0,1455,416,530x559,layout=java.awt.BorderLayout,title=Korge,resizable,normal,defaultCloseOperation=HIDE_ON_CLOSE,rootPane=javax.swing.JRootPane[,9,38,512x512,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
#25: GL_VERSION: 3.3.0 NVIDIA 471.11, GL_VENDOR: NVIDIA Corporation
#25: GL_RED_BITS: 0, GL_GREEN_BITS: 0, GL_BLUE_BITS: 0, GL_ALPHA_BITS: 0, GL_DEPTH_BITS: 0, GL_STENCIL_BITS: 0
#25: requestCoreProfile=true, isCore=true, extensions=390
swapIntervalEXT: Proxy interface to native function@0x7ffc0e1d1e80 (com.soywiz.korgw.win32.Win32OpenglContext$SwapIntervalCallback)
#25: glGetError after glGenVertexArrays
```

The game still seems to work though.

A second probably unrelated thing worth noting is that the readme says

> Inside IntelliJ you can go to the src/commonMain/kotlin/main.kt file and press the green ▶️ icon that appears to the left of the suspend fun main() line.

But there is no such thing in my IntelliJ

![image](https://user-images.githubusercontent.com/123374/145328943-fb03e62a-2f70-4ac8-baa0-496fa03962c9.png)

and creating a Kotlin run configuration doesn't seem to accept `main()`

![image](https://user-images.githubusercontent.com/123374/145329066-358d52c0-d24c-4170-b355-fe6ed83aafdc.png)

I'm reporting these both in the same issue since I'm not sure if it's something related to my setup being broken.

Running on `OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)`

**Comment by soywiz** [comment]
Everything looks expected except `#25: glGetError after glGenVertexArrays` that looks a bit strange. I will investigate that one

The play button is unrelated to that issue. In the commonMain source set the main method doesn't have the play button right now

**Comment by MateuszKunkel** [comment]
> Everything looks expected except `#25: glGetError after glGenVertexArrays` that looks a bit strange. I will investigate that one
> 
> The play button is unrelated to that issue. In the commonMain source set the main method doesn't have the play button right now

i have the same problem with GenVertexArrays, and im still wondering what does it do... did you menage to "investigate" and reach anything with that bro?
