### ISSUE TITLE
iOS Build error: error: no visible @interface for 'GameMainKorgwIosGameWindow' declares the selector 'frame'

### ISSUE THREAD

**Issue by gilbert-jolly** [korlibs/korge-hello-world#9]
CompileC /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/Objects-normal/x86_64/ViewController.o /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app/ViewController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'app-X64-Debug' from project 'app')
    cd /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios10.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu11 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Index/DataStore -iquote /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/unnamed-generated-files.hmap -I/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/unnamed-own-target-headers.hmap -I/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/unnamed-all-target-headers.hmap -iquote /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/unnamed-project-headers.hmap -I/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Products/Debug-iphonesimulator/include -I/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/DerivedSources-normal/x86_64 -I/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/DerivedSources/x86_64 -I/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/DerivedSources -F/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Products/Debug-iphonesimulator -F../../bin/iosX64/debugFramework -MMD -MT dependencies -MF /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/Objects-normal/x86_64/ViewController.d --serialize-diagnostics /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/Objects-normal/x86_64/ViewController.dia -c /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app/ViewController.m -o /Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app.xcodeproj/build/Build/Intermediates.noindex/app.build/Debug-iphonesimulator/app-X64-Debug.build/Objects-normal/x86_64/ViewController.o
/Users/gilbertjolly/Desktop/korge-hello-world-master/build/platforms/ios/app/ViewController.m:85:27: error: no visible @interface for 'GameMainKorgwIosGameWindow' declares the selector 'frame'
        [_gameWindow2.gameWindow frame];
         ~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~

**Comment by soywiz** [comment]
Yeah I had the same issue and fixed it yesterday in 1.13.0.0. It seems that Kotlin/Native changed at some point a small thing in the swift/objective-c interop.
There is a couple of things to fix, so I will release 1.13.0.1 later today.
